interface RegistroMorfometricoSirenio {
  extremoHocicoAExtremoAletaCaudalL: string;
  extremoHocicoAExtremoAletaCaudalC: string;
  extremoHocicoACentroAno: string;
  extremoHocicoAAberturaGenital: string;
  extremoHocicoACentroOmbligo: string;
  extremoHocicoAOrigenAnteriorDeAletasPectorales: string;
  extremoHocicoACentroOjo: string;
  extremoHocicoACentroMeatoAuditivoExterno: string;
  centroOjoACentroMeatoAuditivoExterno: string;
  distanciaOjoAOjoDorso: string;
  centroOjoAlCentroAberturaNasal: string;
  aletaPectoralOrigenAnteriorAlExtremo: string;
  aletaPectoralDeAxilaAlExtremo: string;
  anchoMaxAletaPectoral: string;
  longuitudPerpenticularTetillasDerechas: string;
  longuitudPerpenticularTetillasIzquierdas: string;
  baseAletaCaudalAlExtremo: string;
  anchoMaxAletaCaudal: string;
  diametroNivelDeBaseAletaCaudal: string;
  diametroNivelAno: string;
  diametroNivelOmbligo: string;
  diametroNivelAxila: string;
  grosorPielDorsal: string;
  grosorPielLateral: string;
  grosorPielVentral: string;
  grosorCapasGrasaSuperiorDerecha: string;
  grosorCapasGrasaSuperiorIzquierda: string;
  grosorCapasGrasaInferiorDerecha: string;
  grosorCapasGrasaInferiorIzquierda: string;
  responsablesMorfometria: string;
  responsablesFormatoE1: string;
  grosorCapasGrasaExternaDorsal: string;
  grosorCapasGrasaExternaLateral: string;
  grosorCapasGrasaExternaVentral: string;
  grosorCapasGrasaInternaDorsal: string;
  grosorCapasGrasaInternaLateral: string;
  grosorCapasGrasaInternaVentral: string;
  numeroDientesSuperiorDerecha: string;
  numeroDientesSuperiorIzquierda: string;
  numeroDientesInferiorDerecha: string;
  numeroDientesInferiorIzquierda: string;
}

export default RegistroMorfometricoSirenio;
