CREATE TABLE `acciones` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`autoridades` text,
	`telefonoAutoridades` text,
	`morfometria` integer,
	`necropsia` integer,
	`disposicionDelCadaver` integer,
	`disposicionOtro` text,
	`posibleCausaDelVaramiento` text,
	`posibleCausaDeMuerte` text,
	`participantes` text,
	`observaciones` text,
	`tipoDeMuestras` text,
	`especimen_id` integer,
	FOREIGN KEY (`especimen_id`) REFERENCES `especimen`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `ambiente` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`temperaturaAmbiente` integer,
	`precipitacionHoy` integer,
	`temperaturaSupMar` integer,
	`marea` integer,
	`mareaMedida` integer,
	`direccionCorriente` integer,
	`direccionDelViento` integer,
	`velocidadDelViento` integer,
	`nubosidad` integer,
	`oleaje` integer,
	`beaufort` integer,
	`precipitacionTormentaPrevia` integer,
	`anormalidadGeomagnetica` integer,
	`mareaRoja` integer DEFAULT 0,
	`anormalidadEnLaPesca` text,
	`aviso_id` integer,
	FOREIGN KEY (`aviso_id`) REFERENCES `avisos`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `aviso_idx` ON `ambiente` (`aviso_id`);--> statement-breakpoint
CREATE TABLE `avisos` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`nombre` text,
	`nombreObservador` text,
	`telefono` text,
	`facilAcceso` integer DEFAULT 0,
	`acantilado` integer DEFAULT 0,
	`sustrato` integer,
	`lugarDondeSeVio` integer,
	`fechaDeAvistamiento` text,
	`tipoDeAnimal` integer,
	`observaciones` text,
	`condicionDeAnimal` integer,
	`cantidadDeAnimales` integer,
	`informacionDeLocalizacion` text,
	`latitud` text,
	`longitud` text,
	`fotografia` text
);
--> statement-breakpoint
CREATE TABLE `especie` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`nombre` text,
	`nombreLatin` text,
	`taxa` integer,
	`familia` integer
);
--> statement-breakpoint
CREATE TABLE `especimen` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`latitud` text,
	`longitud` text,
	`condicion` integer,
	`longitudTotalRectilinea` text,
	`peso` text,
	`sexo` integer,
	`grupoDeEdad` integer,
	`orientacionDelEspecimen` text,
	`sustrato` integer,
	`otroSustrato` text,
	`heridasBala` text,
	`heridasBalaFoto` text,
	`presenciaDeRedes` text,
	`presenciaDeRedesFoto` text,
	`mordidas` text,
	`mordidasFoto` text,
	`golpes` text,
	`golpesFoto` text,
	`otroTipoDeHeridas` text,
	`otroTipoDeHeridasFoto` text,
	`especie_id` integer,
	`aviso_id` integer,
	`varamiento_masivo_id` integer,
	`recorrido_id` integer,
	FOREIGN KEY (`especie_id`) REFERENCES `especie`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`aviso_id`) REFERENCES `avisos`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`varamiento_masivo_id`) REFERENCES `varamiento_masivo`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`recorrido_id`) REFERENCES `recorrido`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `localizacion` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`pais` text,
	`estado` text,
	`ciudad` text,
	`localidad` text,
	`informacionAdicional` text,
	`latitud` real NOT NULL,
	`longitud` real NOT NULL
);
--> statement-breakpoint
CREATE TABLE `misticeto` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`NumeroDeBarbas` text,
	`BarbasColor` text,
	`BarbaLargo` text,
	`BarbaAncho` text,
	`M1LongitudTotalLR` text,
	`M1LongitudTotalC` text,
	`M2LongitudRostroAlCentroDelAnoLR` text,
	`M2LongitudRostroAlCentroDelAnoC` text,
	`M3LongitudRostroAlCentroDeLaAberturaGenitalLR` text,
	`M3LongitudRostroAlCentroDeLaAberturaGenitalC` text,
	`M4LongitudDelRostroALosPlieguesGularesLR` text,
	`M4LongitudDelRostroALosPlieguesGularesC` text,
	`M5LongitudDelRostroAlCentroDelOmbligoLR` text,
	`M5LongitudDelRostroAlCentroDelOmbligoC` text,
	`M6LongitudDelRostroAPuntaDeAletaDorsalLR` text,
	`M7LongitudDelRostroAAletaDorsalEnParteAnteriorLR` text,
	`M7LongitudDelRostroAAletaDorsalEnParteAnteriorC` text,
	`M8LongitudDelRostroALaInsercionDeLaAletaPectoralLR` text,
	`M8LongitudDelRostroALaInsercionDeLaAletaPectoralC` text,
	`M9LongitudDelRostroAlCentroDelOrificioRespiratorioLR` text,
	`M9LongitudDelRostroAlCentroDelOrificioRespiratorioC` text,
	`M10LongitudDelRostroAlCentroDelOjoLR` text,
	`M10LongitudDelRostroAlCentroDelOjoC` text,
	`M11LongitudDelRostroAlCentroDelOjoLR` text,
	`M11LongitudDelRostroAlCentroDelOjoC` text,
	`M12LongitudDelRostroALaComisuraDeLaBocaLR` text,
	`M13AnchoMaximoDelRostroLR` text,
	`M14NumeroDePlieguesGularesLR` text,
	`M15NumeroDeProtuberanciasDorsalesLR` text,
	`M16ProyeccionDelMaxilarLR` text,
	`M17DistanciaMaximaDeOjoAOjoC` text,
	`M18AnchoMaximoDelOjoC` text,
	`M19LongitudMaximaDelOjoC` text,
	`M20LongitudMaximaDelCentroDelOjoALaComisuraDeLaBocaLR` text,
	`M20LongitudMaximaDelCentroDelOjoALaComisuraDeLaBocaC` text,
	`M21LongitudMaximaDelCentroDelOjoAlCentroDelOidoLR` text,
	`M21LongitudMaximaDelCentroDelOjoAlCentroDelOidoC` text,
	`M22LongitudMaximaDelCentroDelOjoAlCentroDeLosOrificiosRespiratoriosLR` text,
	`M22LongitudMaximaDelCentroDelOjoAlCentroDeLosOrificiosRespiratoriosC` text,
	`M23LongitudMaximaDeLosOrificiosRespiratoriosC` text,
	`M24AnchoMaximoDeLosOrificiosRespiratoriosC` text,
	`M25AnchoMaximoDeLaAletaPectoralLR` text,
	`M26LongitudMaximaDeLaAletaPectoralEnLaParteAnteriorLR` text,
	`M27LongitudMaximaDeLaAletaPectoralEnLaPartePosteriorLR` text,
	`M28AlturaDeLaAletaDorsalLR` text,
	`M29LongitudDeLaBaseDeLaAletaDorsalLR` text,
	`M30LongitudDeLaAletaCaudalLR` text,
	`M31AnchoDelLobuloCaudalLR` text,
	`M32ProfundidadDeLaEscotaduraLR` text,
	`M33LongitudDeLaEscotaduraAlAnoLR` text,
	`M34LongitudDeLaEscotaduraALaAberturaGenitalLR` text,
	`M35LongitudDeLaEscotaduraAlOmbligoLR` text,
	`M35LongitudDeLaEscotaduraAlOmbligoC` text,
	`M36CircunferenciaDelCuerpoDetrásDeLasPectoralesC` text,
	`M37CircunferenciaDelCuerpoANivelDelOmbligoC` text,
	`M38CircunferenciaDelCuerpoANivelDeLaAberturaGenitalC` text,
	`M39CircunferenciaDelCuerpoEnElPedunculoCaudalC` text,
	`M40LongitudDeLaAberturaMamariaC` text,
	`M41LongitudDeLaAberturaGenitalC` text,
	`M42LongitudDeLaAberturaAnalC` text,
	`especimen_id` integer,
	FOREIGN KEY (`especimen_id`) REFERENCES `especimen`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `odontoceto` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`maxilarIzquierdo` text,
	`maxilarDerecho` text,
	`mandibulaIzquierda` text,
	`mandibulaDerecha` text,
	`m1LongitudTotalLR` text,
	`m1LongitudTotalC` text,
	`m2LongitudRostroAlCentroDelAnoLR` text,
	`m2LongitudRostroAlCentroDelAnoC` text,
	`m3LongitudRostroAlCentroDeLaAberturaGenitalLR` text,
	`m3LongitudRostroAlCentroDeLaAberturaGenitalC` text,
	`m4LongitudDelRostroAlCentroDelOmbligoLR` text,
	`m4LongitudDelRostroAlCentroDelOmbligoC` text,
	`m5LongitudDelRostroAPuntaDeAletaDorsalLR` text,
	`m6LongitudDelRostroAAletaDorsalEnParteAnteriorLR` text,
	`m6LongitudDelRostroAAletaDorsalEnParteAnteriorC` text,
	`m7LongitudDelRostroAAletaPectoralEnparteAnteriorLR` text,
	`m7LongitudDelRostroAAletaPectoralEnparteAnteriorC` text,
	`m8LongitudDelRostroAlCentroDelOrificioRespiratorioLR` text,
	`m8LongitudDelRostroAlCentroDelOrificioRespiratorioC` text,
	`m9LongitudDeLaPuntaDelRostroALaBaseDelRostroLR` text,
	`m9LongitudDeLaPuntaDelRostroALaBaseDelRostroC` text,
	`m10LongitudDelRostroAlCentroDelOidoLR` text,
	`m10LongitudDelRostroAlCentroDelOidoC` text,
	`m11LongitudDelRostroAlCentroDelOjoLR` text,
	`m11LongitudDelRostroAlCentroDelOjoC` text,
	`m12LongitudDelRostroALaComisuraDeLaBocaLR` text,
	`m12LongitudDelRostroALaComisuraDeLaBocaC` text,
	`m13AnchoMaximoDelRostroLR` text,
	`m14ProyeccionDelMaxilarOMandibulaLR` text,
	`m15DistanciaMaximaDeOjoAOjoC` text,
	`m16AnchoMaximoDelOjoC` text,
	`m17LongitudMaximaDelOjoC` text,
	`m18LongitudMaximaDelCentroDelOjoALaComisuraDeLaBocaLR` text,
	`m18LongitudMaximaDelCentroDelOjoALaComisuraDeLaBocaC` text,
	`m19LongitudMaximaDelCentroDelOjoAlCentroDelOidoLR` text,
	`m19LongitudMaximaDelCentroDelOjoAlCentroDelOidoC` text,
	`m20LongitudMaximaDelCentroDelOjoAlCentroDelOrificioRespiratorioLR` text,
	`m20LongitudMaximaDelCentroDelOjoAlCentroDelOrificioRespiratorioC` text,
	`m21M21LongitudMaximaDelOrificioRespiratorioC` text,
	`m22AnchoMaximoDelOrificioRespiratorioC` text,
	`m23AnchoMaximoDeLaAletaPectoralLR` text,
	`m24LongitudMaximaDeLaAletaPectoralEnLaParteAnteriorLR` text,
	`m25LongitudMaximaDeLaAletaPectoralEnLaPartePosteriorLR` text,
	`m26AlturaDeLaAletaDorsalLR` text,
	`m27LongitudDeLaBaseDeLaAletaDorsalLR` text,
	`m28LongitudDeLaAletaCaudalLR` text,
	`m29AnchoDelLobuloCaudalLR` text,
	`m30ProfundidadDeLaEscotaduraLR` text,
	`m31LongitudDeLaEscotaduraAlAnoLR` text,
	`m31LongitudDeLaEscotaduraAlAnoC` text,
	`m32LongitudDeLaEscotaduraALaAberturaGenitalLR` text,
	`m32LongitudDeLaEscotaduraALaAberturaGenitalC` text,
	`m33LongitudDeLaEscotaduraAlOmbligoLR` text,
	`m33LongitudDeLaEscotaduraAlOmbligoC` text,
	`m34CircunferenciaDelCuerpoDetrásDeLasPectoralesC` text,
	`m35CircunferenciaMaximaC` text,
	`m36CircunferenciaDelCuerpoANivelDelOmbligoC` text,
	`m37CircunferenciaDelCuerpoANivelDeLaAberturaGenitalC` text,
	`m38CircunferenciaDelCuerpoEnElPedunculoCaudalC` text,
	`m39LongitudDeLaAberturaMamariaC` text,
	`m40LongitudDeLaAberturaGenitalC` text,
	`m41LongitudDeLaAberturaAnalC` text,
	`especimen_id` integer,
	FOREIGN KEY (`especimen_id`) REFERENCES `especimen`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `organismo` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tasaDeRespiracion` text,
	`pulso` text,
	`temperatura` text,
	`antesDeVararse` text,
	`varado` text,
	`reflotacion` integer,
	`despuesDeReflotar` text,
	`animalTransferido` integer,
	`lugarDeRehabilitacion` text,
	`despuesDeVararse` text,
	`especimen_id` integer,
	FOREIGN KEY (`especimen_id`) REFERENCES `especimen`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `pinnipedo` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`lrNarizAColaCm` text,
	`lcNarizAColaCm` text,
	`cCuerpoDetrasDePectorales` text,
	`cCuerpoANivelDelOmbligo` text,
	`lNarizAlCentroDelOjo` text,
	`lNarizAlCentroDelOido` text,
	`lAletaPectoralEnParteAnterior` text,
	`aAletaPectoralANivelAxila` text,
	`aMaximoDeAletapectora` text,
	`lAletaPosteriorParteAnterior` text,
	`anchoMaximoAletaPosterior` text,
	`lCola` text,
	`eCapaDeGrasa` text,
	`cCraneoAlturaDeOrejas` text,
	`aRostro` text,
	`aCabeza` text,
	`lCabeza` text,
	`lPoscaninosSuperiores` text,
	`anchoInterorbital` text,
	`anchoCigomatico` text,
	`anchoCondilobasal` text,
	`maxilarIzquierdoPosCanino` text,
	`maxilarIzquierdoCanino` text,
	`maxilarIzquierdoIncisivo` text,
	`maxilarDerechoPosCanino` text,
	`maxilarDerechoCanino` text,
	`maxilarDerechoIncisivo` text,
	`mandibulaIzquierdoPosCanino` text,
	`mandibulaIzquierdoCanino` text,
	`mandibulaIzquierdoIncisivo` text,
	`mandibulaDerechoPosCanino` text,
	`mandibulaDerechoCanino` text,
	`mandibulaDerechoIncisivo` text,
	`especimen_id` integer,
	FOREIGN KEY (`especimen_id`) REFERENCES `especimen`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `recorrido` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`fecha` text,
	`horaInicio` text,
	`horaFin` text,
	`coordenada_inicio_id` integer,
	`coordenada_fin_id` integer,
	`referenciasInicio` text,
	`referenciasFin` text,
	`distanciaRecorrido` real,
	`observaciones` text,
	`participantes` text,
	`zonaSeguimiento` text,
	`ruta` text,
	`reportesMasivos` text,
	FOREIGN KEY (`coordenada_inicio_id`) REFERENCES `localizacion`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`coordenada_fin_id`) REFERENCES `localizacion`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `sirenio` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`extremoHocicoAExtremoAletaCaudalL` text,
	`extremoHocicoAExtremoAletaCaudalC` text,
	`extremoHocicoACentroAno` text,
	`extremoHocicoAAberturaGenital` text,
	`extremoHocicoACentroOmbligo` text,
	`extremoHocicoAOrigenAnteriorDeAletasPectorales` text,
	`extremoHocicoACentroOjo` text,
	`extremoHocicoACentroMeatoAuditivoExterno` text,
	`centroOjoACentroMeatoAuditivoExterno` text,
	`distanciaOjoAOjoDorso` text,
	`centroOjoAlCentroAberturaNasal` text,
	`aletaPectoralOrigenAnteriorAlExtremo` text,
	`aletaPectoralDeAxilaAlExtremo` text,
	`anchoMaxAletaPectoral` text,
	`longuitudPerpenticularTetillasDerechas` text,
	`longuitudPerpenticularTetillasIzquierdas` text,
	`baseAletaCaudalAlExtremo` text,
	`anchoMaxAletaCaudal` text,
	`diametroNivelDeBaseAletaCaudal` text,
	`diametroNivelAno` text,
	`diametroNivelOmbligo` text,
	`diametroNivelAxila` text,
	`grosorPielDorsal` text,
	`grosorPielLateral` text,
	`grosorPielVentral` text,
	`grosorCapasGrasaSuperiorDerecha` text,
	`grosorCapasGrasaSuperiorIzquierda` text,
	`grosorCapasGrasaInferiorDerecha` text,
	`grosorCapasGrasaInferiorIzquierda` text,
	`responsablesMorfometria` text,
	`responsablesFormatoE1` text,
	`grosorCapasGrasaExternaDorsal` text,
	`grosorCapasGrasaExternaLateral` text,
	`grosorCapasGrasaExternaVentral` text,
	`grosorCapasGrasaInternaDorsal` text,
	`grosorCapasGrasaInternaLateral` text,
	`grosorCapasGrasaInternaVentral` text,
	`numeroDientesSuperiorDerecha` text,
	`numeroDientesSuperiorIzquierda` text,
	`numeroDientesInferiorDerecha` text,
	`numeroDientesInferiorIzquierda` text,
	`especimen_id` integer,
	FOREIGN KEY (`especimen_id`) REFERENCES `especimen`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `varamiento_masivo` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`avesMuertas` integer,
	`avesMuertasCantidad` text,
	`pecesMuertos` integer,
	`pecesMuertosCantidad` text,
	`numeroTotalDeAnimales` text,
	`subGrupos` text,
	`animalesVivos` text,
	`animalesMuertos` text,
	`observaciones` text,
	`aviso_id` integer,
	FOREIGN KEY (`aviso_id`) REFERENCES `avisos`(`id`) ON UPDATE no action ON DELETE no action
);
